from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol

from vector_editor.domain.base import Shape


class ShapeRepository(Protocol):
    def next_id(self) -> int: ...
    def add(self, shape: Shape) -> Shape: ...
    def list_all(self) -> Iterable[Shape]: ...
    def exists(self, shape_id: int) -> bool: ...
    def remove(self, shape_id: int) -> Shape: ...